name: Manual runner

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master  "]
  workflow_dispatch:

# jobs:
#   job2:
#       runs-on: ubuntu-latest
#       steps:
#        - uses: actions/checkout@v3

#        - name: Run a one-line script
#           run: echo this is my name

#        - name: Run a multi-line script
#           run: |
#             echo this is multi line,
#             echo this is multi line  

jobs:
  job_first:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo now this code is runnig through my windows mechine of my laptop

      - name: Run a multi-line script
        run: |
          echo multi line 1 
          echo multi line 2 

        

