name: Manual runner

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master  "]
  workflow_dispatch:

jobs:
  windows:
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v3

       - name: Run a one-line script
          run: echo this is windows runner code

       - name: Run a multi-line script
          run: |
            echo this is multi line,
            echo this is multi line  
        

